version: "3.5"
services:
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi_network
    volumes:
      - strapi-data:/data/db

  api:
    build:
      context: ./app/
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.cache
      - /app/build
      - static-files:/app/public
    networks:
      - strapi_network
    depends_on:
      - db

networks:
  strapi_network:

volumes:
  strapi-data:
  static-files:
